In [28]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

import pandas as pd
import numpy as np

In [29]:
np.random.seed(123)
df = pd.DataFrame({'feature1' : np.random.normal(10, 1.5, 20),
              'feature2'  : np.random.choice(['dog', 'cat', 'lion'], size = 20, p = [0.3, 0.3, .4])
             })

In [30]:
df.head()

feature1 feature2
0   8.371554     lion
1  11.496018     lion
2  10.424468     lion
3   7.740558      cat
4   9.132100      cat

In [31]:
encoder1 = LabelEncoder()

In [32]:
encoder1.fit_transform(df.feature2)

array([2, 2, 2, 0, 0, 1, 1, 2, 1, 0, 0, 0, 0, 0, 0, 2, 2, 0, 2, 1])

In [33]:
# ordinal encoder

In [34]:
encoder2 = OrdinalEncoder()

In [35]:
encoder2.fit_transform(df.feature2)

ValueError: Expected 2D array, got 1D array instead:
array=['lion' 'lion' 'lion' 'cat' 'cat' 'dog' 'dog' 'lion' 'dog' 'cat' 'cat'
 'cat' 'cat' 'cat' 'cat' 'lion' 'lion' 'cat' 'lion' 'dog'].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [36]:
encoder2.fit_transform(np.array(df.feature2).reshape(-1,1))

array([[2.],
       [2.],
       [2.],
       [0.],
       [0.],
       [1.],
       [1.],
       [2.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [2.],
       [2.],
       [0.],
       [2.],
       [1.]])

In [37]:
#one hot encoder

In [38]:
encoder3 = OneHotEncoder()

In [40]:
result = encoder3.fit_transform(np.array(df.feature2).reshape(-1,1))

In [41]:
result.toarray()

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [42]:
encoder3.categories_

[array(['cat', 'dog', 'lion'], dtype=object)]